---
name: test
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        #- uses: actions/checkout@v4

        # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
      - name: rrun a second job
        run: echo running a second job
      - name: runninga multi line job
        run : |
          echo runninga multi line,
          echo second lint.
          